name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: trunk-action
      uses: jetli/trunk-action@v0.1.0
    - name: Build
      run: trunk build --release
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        publish-dir: "dist"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
